version: '3.9'

services:
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: Password
    volumes:
      - C:/Users/Murav/Documents/Docker-server-Postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: Password@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Password
    ports:
      - "8080:80"
    depends_on:
      - db